Rename System.Text.Json.Serialization.JsonPropertyName for SlackApiMessage.PostAt from "username" to "post_at"
Resolves the following error

    System.InvalidOperationException: The JSON property name for 'Slack.MessageBuilder.Objects.SlackApiMessage.username' collides with another property.